[theme]
primaryColor = "#f63366"
# backgroundColor = "#0f1117"
backgroundColor = "#0f1117"
# secondaryBackgroundColor = "#27262f"
secondaryBackgroundColor = "#27262f"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true